TEST_CASE := litex-rocket
TOP := olimex_gatemate_a1_evb
YOSYS_PARAM := -nomx8
VERILOG_FILES := \
	freechips.rocketchip.system.LitexConfig_small_1_1.v \
	freechips.rocketchip.system.LitexConfig_small_1_1.behav_srams.v \
	plusarg_reader.v \
	AsyncResetReg.v \
	EICG_wrapper.v \
	olimex_gatemate_a1_evb.v

include ../makefile.inc
