TEST_CASE := litex-eth
TOP := olimex_gatemate_a1_evb
YOSYS_PARAM := -nomx8 -nomult
VERILOG_FILES := \
	../lib/femtosoc/PROCESSOR/femtorv32_quark.v \
	olimex_gatemate_a1_evb.v

include ../makefile.inc
