TEST_CASE := litex-flash-4x
TOP := colognechip_gatemate_evb
YOSYS_PARAM := -nomx8 -nomult
PR_OPTS := +uCIO
VERILOG_FILES := \
	../lib/femtosoc/PROCESSOR/femtorv32_quark.v \
	colognechip_gatemate_evb.v

include ../makefile.inc
