TEST_CASE := galaksija
TOP := galaksija_olimex_gatemate
YOSYS_PARAM := -nomx8 -nomult
VERILOG_FILES := \
	galaksija_olimex_gatemate.v \
	gatemate_10MHz_25MHz_pll.v \
	galaksija.v \
	rom_memory.v \
	font_rom.v \
	video.v \
	uart_rx.v \
	tv80_alu.v \
	tv80_core.v \
	tv80_mcode.v \
	tv80n.v \
	tv80_reg.v \
	bram_true2p_2clk.v
include ../makefile.inc
