TEST_CASE := atom
TOP := atom
YOSYS_PARAM := -nomx8
VERILOG_FILES := \
	src/atom.v \
	src/cpu.v \
	src/ALU.v \
	src/mc6847.v \
	src/charrom.v \
	src/vid_ram.v \
	src/ram.v \
	src/keyboard.v \
	src/ps2_intf.v \
	src/flashmem.v \
	src/m6522.v \
	src/spi.v \
	src/rom_c000_ffff.v \
	src/sid/sid_6581.v \
	src/sid/sid_coeffs.v \
	src/sid/sid_components.v \
	src/sid/sid_filters.v \
	src/sid/sid_voice.v \
	../lib/fpgalibs/clocks/gatemate_25MHz_pll.v

include ../makefile.inc
