TEST_CASE := litex-lm32
TOP := olimex_gatemate_a1_evb
YOSYS_PARAM := -nomx8 -nomult
VERILOG_FILES := \
	lm32/lm32_cpu.v \
	lm32/lm32_instruction_unit.v \
	lm32/lm32_decoder.v \
	lm32/lm32_load_store_unit.v \
	lm32/lm32_adder.v \
	lm32/lm32_addsub.v \
	lm32/lm32_logic_op.v \
	lm32/lm32_shifter.v \
	lm32/lm32_multiplier.v \
	lm32/lm32_mc_arithmetic.v \
	lm32/lm32_interrupt.v \
	lm32/lm32_ram.v \
	lm32/lm32_dp_ram.v \
	lm32/lm32_icache.v \
	lm32/lm32_dcache.v \
	lm32/lm32_debug.v \
	lm32/lm32_itlb.v \
	lm32/lm32_dtlb.v \
	olimex_gatemate_a1_evb.v
include ../makefile.inc
