TEST_CASE := vga-racingbeam
TOP := top_bounce
#TOP := top_colour_cycle
#TOP := top_hello
#TOP := top_hitomezashi
#TOP := top_rasterbars
YOSYS_PARAM := -nomx8
VERILOG_FILES := \
	top_bounce.sv \
	top_colour_cycle.sv \
	top_hello.sv \
	top_hitomezashi.sv \
	top_rasterbars.sv \
	simple_480p.sv \
	../lib/clock/gatemate/clock_480p.sv \
	../lib/display/display_480p.sv
include ../makefile.inc
