// THIS FILE IS AUTOGENERATED BY corescorecore_gen
// ANY MANUAL CHANGES WILL BE LOST
`default_nettype none
module corescorecore
   (input  wire       i_clk,
    input  wire       i_rst,
    output wire [7:0] o_tdata,
    output wire       o_tlast,
    output wire       o_tvalid,
    input  wire       i_tready);

wire [199:0] tdata;
wire  [24:0] tlast;
wire  [24:0] tvalid;
wire  [24:0] tready;

base
  #(.memfile ("hex/core_0.hex"),
    .memsize (256))
 core_0
   (.i_clk    (i_clk),
    .i_rst    (i_rst),
    .o_tdata  (tdata[7:0]),
    .o_tlast  (tlast[0]),
    .o_tvalid (tvalid[0]),
    .i_tready (tready[0]));

base
  #(.memfile ("hex/core_1.hex"),
    .memsize (256))
 core_1
   (.i_clk    (i_clk),
    .i_rst    (i_rst),
    .o_tdata  (tdata[15:8]),
    .o_tlast  (tlast[1]),
    .o_tvalid (tvalid[1]),
    .i_tready (tready[1]));

base
  #(.memfile ("hex/core_2.hex"),
    .memsize (256))
 core_2
   (.i_clk    (i_clk),
    .i_rst    (i_rst),
    .o_tdata  (tdata[23:16]),
    .o_tlast  (tlast[2]),
    .o_tvalid (tvalid[2]),
    .i_tready (tready[2]));

base
  #(.memfile ("hex/core_3.hex"),
    .memsize (256))
 core_3
   (.i_clk    (i_clk),
    .i_rst    (i_rst),
    .o_tdata  (tdata[31:24]),
    .o_tlast  (tlast[3]),
    .o_tvalid (tvalid[3]),
    .i_tready (tready[3]));

base
  #(.memfile ("hex/core_4.hex"),
    .memsize (256))
 core_4
   (.i_clk    (i_clk),
    .i_rst    (i_rst),
    .o_tdata  (tdata[39:32]),
    .o_tlast  (tlast[4]),
    .o_tvalid (tvalid[4]),
    .i_tready (tready[4]));

base
  #(.memfile ("hex/core_5.hex"),
    .memsize (256))
 core_5
   (.i_clk    (i_clk),
    .i_rst    (i_rst),
    .o_tdata  (tdata[47:40]),
    .o_tlast  (tlast[5]),
    .o_tvalid (tvalid[5]),
    .i_tready (tready[5]));

base
  #(.memfile ("hex/core_6.hex"),
    .memsize (256))
 core_6
   (.i_clk    (i_clk),
    .i_rst    (i_rst),
    .o_tdata  (tdata[55:48]),
    .o_tlast  (tlast[6]),
    .o_tvalid (tvalid[6]),
    .i_tready (tready[6]));

base
  #(.memfile ("hex/core_7.hex"),
    .memsize (256))
 core_7
   (.i_clk    (i_clk),
    .i_rst    (i_rst),
    .o_tdata  (tdata[63:56]),
    .o_tlast  (tlast[7]),
    .o_tvalid (tvalid[7]),
    .i_tready (tready[7]));

base
  #(.memfile ("hex/core_8.hex"),
    .memsize (256))
 core_8
   (.i_clk    (i_clk),
    .i_rst    (i_rst),
    .o_tdata  (tdata[71:64]),
    .o_tlast  (tlast[8]),
    .o_tvalid (tvalid[8]),
    .i_tready (tready[8]));

base
  #(.memfile ("hex/core_9.hex"),
    .memsize (256))
 core_9
   (.i_clk    (i_clk),
    .i_rst    (i_rst),
    .o_tdata  (tdata[79:72]),
    .o_tlast  (tlast[9]),
    .o_tvalid (tvalid[9]),
    .i_tready (tready[9]));

base
  #(.memfile ("hex/core_10.hex"),
    .memsize (256))
 core_10
   (.i_clk    (i_clk),
    .i_rst    (i_rst),
    .o_tdata  (tdata[87:80]),
    .o_tlast  (tlast[10]),
    .o_tvalid (tvalid[10]),
    .i_tready (tready[10]));

base
  #(.memfile ("hex/core_11.hex"),
    .memsize (256))
 core_11
   (.i_clk    (i_clk),
    .i_rst    (i_rst),
    .o_tdata  (tdata[95:88]),
    .o_tlast  (tlast[11]),
    .o_tvalid (tvalid[11]),
    .i_tready (tready[11]));

base
  #(.memfile ("hex/core_12.hex"),
    .memsize (256))
 core_12
   (.i_clk    (i_clk),
    .i_rst    (i_rst),
    .o_tdata  (tdata[103:96]),
    .o_tlast  (tlast[12]),
    .o_tvalid (tvalid[12]),
    .i_tready (tready[12]));

base
  #(.memfile ("hex/core_13.hex"),
    .memsize (256))
 core_13
   (.i_clk    (i_clk),
    .i_rst    (i_rst),
    .o_tdata  (tdata[111:104]),
    .o_tlast  (tlast[13]),
    .o_tvalid (tvalid[13]),
    .i_tready (tready[13]));

base
  #(.memfile ("hex/core_14.hex"),
    .memsize (256))
 core_14
   (.i_clk    (i_clk),
    .i_rst    (i_rst),
    .o_tdata  (tdata[119:112]),
    .o_tlast  (tlast[14]),
    .o_tvalid (tvalid[14]),
    .i_tready (tready[14]));

base
  #(.memfile ("hex/core_15.hex"),
    .memsize (256))
 core_15
   (.i_clk    (i_clk),
    .i_rst    (i_rst),
    .o_tdata  (tdata[127:120]),
    .o_tlast  (tlast[15]),
    .o_tvalid (tvalid[15]),
    .i_tready (tready[15]));

base
  #(.memfile ("hex/core_16.hex"),
    .memsize (256))
 core_16
   (.i_clk    (i_clk),
    .i_rst    (i_rst),
    .o_tdata  (tdata[135:128]),
    .o_tlast  (tlast[16]),
    .o_tvalid (tvalid[16]),
    .i_tready (tready[16]));

base
  #(.memfile ("hex/core_17.hex"),
    .memsize (256))
 core_17
   (.i_clk    (i_clk),
    .i_rst    (i_rst),
    .o_tdata  (tdata[143:136]),
    .o_tlast  (tlast[17]),
    .o_tvalid (tvalid[17]),
    .i_tready (tready[17]));

base
  #(.memfile ("hex/core_18.hex"),
    .memsize (256))
 core_18
   (.i_clk    (i_clk),
    .i_rst    (i_rst),
    .o_tdata  (tdata[151:144]),
    .o_tlast  (tlast[18]),
    .o_tvalid (tvalid[18]),
    .i_tready (tready[18]));

base
  #(.memfile ("hex/core_19.hex"),
    .memsize (256))
 core_19
   (.i_clk    (i_clk),
    .i_rst    (i_rst),
    .o_tdata  (tdata[159:152]),
    .o_tlast  (tlast[19]),
    .o_tvalid (tvalid[19]),
    .i_tready (tready[19]));

base
  #(.memfile ("hex/core_20.hex"),
    .memsize (256))
 core_20
   (.i_clk    (i_clk),
    .i_rst    (i_rst),
    .o_tdata  (tdata[167:160]),
    .o_tlast  (tlast[20]),
    .o_tvalid (tvalid[20]),
    .i_tready (tready[20]));

base
  #(.memfile ("hex/core_21.hex"),
    .memsize (256))
 core_21
   (.i_clk    (i_clk),
    .i_rst    (i_rst),
    .o_tdata  (tdata[175:168]),
    .o_tlast  (tlast[21]),
    .o_tvalid (tvalid[21]),
    .i_tready (tready[21]));

base
  #(.memfile ("hex/core_22.hex"),
    .memsize (256))
 core_22
   (.i_clk    (i_clk),
    .i_rst    (i_rst),
    .o_tdata  (tdata[183:176]),
    .o_tlast  (tlast[22]),
    .o_tvalid (tvalid[22]),
    .i_tready (tready[22]));

base
  #(.memfile ("hex/core_23.hex"),
    .memsize (256))
 core_23
   (.i_clk    (i_clk),
    .i_rst    (i_rst),
    .o_tdata  (tdata[191:184]),
    .o_tlast  (tlast[23]),
    .o_tvalid (tvalid[23]),
    .i_tready (tready[23]));

base
  #(.memfile ("hex/core_24.hex"),
    .memsize (256))
 core_24
   (.i_clk    (i_clk),
    .i_rst    (i_rst),
    .o_tdata  (tdata[199:192]),
    .o_tlast  (tlast[24]),
    .o_tvalid (tvalid[24]),
    .i_tready (tready[24]));

axis_arb_mux
  #(.S_COUNT      (25),
    .DATA_WIDTH   (8),
    .KEEP_ENABLE  (0),
    .KEEP_WIDTH   (1),
    .ID_ENABLE    (0),
    .ID_WIDTH     (8),
    .DEST_ENABLE  (0),
    .DEST_WIDTH   (8),
    .USER_ENABLE  (0),
    .USER_WIDTH   (1),
    .ARB_TYPE     ("ROUND_ROBIN"),
    .LSB_PRIORITY ("HIGH"))
 axis_mux
   (.clk           (i_clk),
    .rst           (i_rst),
    .s_axis_tdata  (tdata),
    .s_axis_tkeep  (25'd0),
    .s_axis_tvalid (tvalid),
    .s_axis_tready (tready),
    .s_axis_tlast  (tlast),
    .s_axis_tid    (200'd0),
    .s_axis_tdest  (200'd0),
    .s_axis_tuser  (25'd0),
    .m_axis_tdata  (o_tdata),
    .m_axis_tkeep  (),
    .m_axis_tvalid (o_tvalid),
    .m_axis_tready (i_tready),
    .m_axis_tlast  (o_tlast),
    .m_axis_tid    (),
    .m_axis_tdest  (),
    .m_axis_tuser  ());

endmodule
