TEST_CASE := litex-fazyrv
TOP := olimex_gatemate_a1_evb
YOSYS_PARAM := -nomx8 -nomult
VERILOG_FILES := \
	FazyRV/rtl/fazyrv_top.sv \
	FazyRV/rtl/fazyrv_pc.sv \
	FazyRV/rtl/fazyrv_cmp.v \
	FazyRV/rtl/fazyrv_rf.sv \
	FazyRV/rtl/fazyrv_spm_a.sv \
	FazyRV/rtl/fazyrv_decode_mem1.sv \
	FazyRV/rtl/fazyrv_decode.sv \
	FazyRV/rtl/fazyrv_ram_dp.sv \
	FazyRV/rtl/fazyrv_rf_lut.sv \
	FazyRV/rtl/fazyrv_csr.sv \
	FazyRV/rtl/fazyrv_alu.sv \
	FazyRV/rtl/fazyrv_cntrl.sv \
	FazyRV/rtl/fazyrv_fadd.v \
	FazyRV/rtl/fazyrv_shftreg.sv \
	FazyRV/rtl/fazyrv_ram_sp.sv \
	FazyRV/rtl/fazyrv_spm_d.sv \
	FazyRV/rtl/fazyrv_core.sv \
	FazyRV/rtl/fazyrv_hadd.v \
	olimex_gatemate_a1_evb.v
include ../makefile.inc
