TEST_CASE := zexall
TOP := top
YOSYS_PARAM := -nomx8 -nomult
VERILOG_FILES := \
	top_zexall.v \
	zexall.v \
	rom_memory.v \
	ram_memory.v \
	simpleuart.v \
	../lib/Z80/tv80n.v \
	../lib/Z80/tv80_reg.v \
	../lib/Z80/tv80_mcode.v \
	../lib/Z80/tv80_core.v \
	../lib/Z80/tv80_alu.v

include ../makefile.inc
