TEST_CASE := msx
TOP := msx
YOSYS_PARAM := -nomx8
VERILOG_FILES := \
	src/msx.v \
	src/gamerom.v \
	src/keyboard.v \
	src/keymap.v \
	src/keyram.v \
	src/keyrom.v \
	src/ps2.v \
	src/ram.v \
	src/rom.v \
	src/video.v \
	src/vram.v \
	../lib/Z80/tv80_core.v \
	../lib/Z80/tv80n.v \
	../lib/Z80/tv80_mcode.v \
	../lib/Z80/tv80_reg.v \
	../lib/Z80/tv80_alu.v \
	../lib/fpgalibs/clocks/gatemate_25MHz_pll.v

include ../makefile.inc
