TEST_CASE := apple1_top
TOP := apple1_top
YOSYS_PARAM := -nomx8 -nomult
VERILOG_FILES := \
	apple1.v \
	clock.v \
	pwr_reset.v \
	ram.v \
	rom_wozmon.v \
	rom_basic.v \
	cpu/arlet_6502.v \
	cpu/arlet/ALU.v \
	cpu/arlet/cpu.v \
	uart/uart.v \
	uart/async_tx_rx.v \
	vga/vga.v \
	vga/vram.v \
	vga/font_rom.v \
	ps2keyboard/debounce.v \
	ps2keyboard/ps2keyboard.v \
	boards/olimex_gatemate/apple1_vga.v \
	boards/olimex_gatemate/gatemate_10MHz_25MHz_pll.v

include ../makefile.inc
