TEST_CASE := vga-color
YOSYS_PARAM := -noaddf
YOSYS_DEFS := -DDISP_640x480_60Hz=1
VERILOG_FILES := top.v ../lib/fpgalibs/graphics/vga_core.v ../lib/fpgalibs/clocks/gatemate_25MHz_pll.v 
include ../makefile.inc
