TEST_CASE := vga-ad-astra
YOSYS_PARAM := -nomx8
#TOP := top_greet_v1
TOP := top_greet
#TOP := top_hello_en
#TOP := top_hello_jp
#TOP := top_lfsr
#TOP := top_space_f
#TOP := top_starfields
VERILOG_FILES := \
	top_greet_v1.sv \
	top_greet.sv \
	top_hello_en.sv \
	top_hello_jp.sv \
	top_lfsr.sv \
	top_space_f.sv \
	top_starfields.sv \
	sprite.sv \
	starfield.sv \
	../lib/clock/gatemate/clock_480p.sv \
	../lib/display/display_480p.sv \
	../lib/maths/lfsr.sv \
	../lib/memory/rom_sync.sv 
include ../makefile.inc
