TEST_CASE := tetris
TOP := top
YOSYS_PARAM := -nomx8
VERILOG_FILES := \
	top.v \
	uart_rx.v \
	uart_tx.v \
	vga_controller.v \
	vga_map_ram.v \
	vga_ram.v \
	vga_wrapper.v \
	debounce.v \
	gatemate_25MHz_pll.v \
	picosoc_noflash.v \
	picorv32.v \
	progmem.v \
	simpleuart.v 

include ../makefile.inc
