TEST_CASE := litex-hyperram
TOP := colognechip_gatemate_evb
YOSYS_PARAM := -nomx8
VERILOG_FILES := \
	../lib/femtosoc/PROCESSOR/femtorv32_quark.v \
	colognechip_gatemate_evb.v

include ../makefile.inc
