TEST_CASE := vga-graphics
TOP := top_colour
#TOP := top_flag_ethiopia
#TOP := top_flag_sweden
#TOP := top_square
YOSYS_PARAM := -nomx8
VERILOG_FILES := \
	top_colour.sv \
	top_flag_ethiopia.sv \
	top_flag_sweden.sv \
	top_square.sv \
	simple_480p.sv \
	../lib/clock/gatemate/clock_480p.sv \
	../lib/display/display_480p.sv
include ../makefile.inc
