TEST_CASE := litex-kianv
TOP := olimex_gatemate_a1_evb
YOSYS_PARAM := -nomx8 -nomult
VERILOG_FILES := \
	kianv_harris_edition/multiplier.v \
	kianv_harris_edition/misa.vh \
	kianv_harris_edition/mcause.vh \
	kianv_harris_edition/divider.v \
	kianv_harris_edition/register_file.v \
	kianv_harris_edition/divider_decoder.v \
	kianv_harris_edition/csr_utilities.vh \
	kianv_harris_edition/datapath_unit.v \
	kianv_harris_edition/multiplier_extension_decoder.v \
	kianv_harris_edition/riscv_defines.vh \
	kianv_harris_edition/control_unit.v \
	kianv_harris_edition/alu.v \
	kianv_harris_edition/load_alignment.v \
	kianv_harris_edition/store_decoder.v \
	kianv_harris_edition/store_alignment.v \
	kianv_harris_edition/main_fsm.v \
	kianv_harris_edition/riscv_priv_csr_status.vh \
	kianv_harris_edition/kianv_harris_mc_edition.v \
	kianv_harris_edition/extend.v \
	kianv_harris_edition/rv32_amo_opcodes.vh \
	kianv_harris_edition/csr_exception_handler.v \
	kianv_harris_edition/csr_decoder.v \
	kianv_harris_edition/alu_decoder.v \
	kianv_harris_edition/multiplier_decoder.v \
	kianv_harris_edition/load_decoder.v \
	kianv_harris_edition/design_elements.v \
	olimex_gatemate_a1_evb.v

include ../makefile.inc
