TEST_CASE := vga-math
TOP := top_graphing
YOSYS_PARAM := -nomx8 -nomult
VERILOG_FILES := \
	top_graphing.sv \
	func_circle.sv \
	func_cubed.sv \
	func_polynomial.sv \
	func_squared.sv \
	../lib/clock/gatemate/clock_480p.sv \
  	../lib/display/display_480p.sv
include ../makefile.inc
