TEST_CASE := vga-nyan
TOP := tt_um_a1k0n_nyancat
YOSYS_PARAM := -nomx8
VERILOG_FILES := \
	tt_um_a1k0n_nyancat.v \
	hvsync_generator.v \
	../lib/fpgalibs/clocks/gatemate_25MHz_pll.v 
include ../makefile.inc
