TEST_CASE := corescore
TOP := corescore_gatemate
YOSYS_PARAM := -nomx8
VERILOG_FILES := \
	serv_1.0.2/rtl/serv_shift.v \
	serv_1.0.2/rtl/serv_bufreg.v \
	serv_1.0.2/rtl/serv_alu.v \
	serv_1.0.2/rtl/serv_csr.v \
	serv_1.0.2/rtl/serv_ctrl.v \
	serv_1.0.2/rtl/serv_decode.v \
	serv_1.0.2/rtl/serv_mem_if.v \
	serv_1.0.2/rtl/serv_rf_if.v \
	serv_1.0.2/rtl/serv_rf_ram_if.v \
	serv_1.0.2/rtl/serv_rf_ram.v \
	serv_1.0.2/rtl/serv_state.v \
	serv_1.0.2/rtl/serv_top.v \
	serv_1.0.2/rtl/serv_rf_top.v \
	verilog-axis_0-r3/rtl/arbiter.v \
	verilog-axis_0-r3/rtl/priority_encoder.v \
	verilog-axis_0-r3/rtl/axis_arb_mux.v \
	verilog-axis_0-r3/rtl/axis_async_fifo.v \
	servant_1.0.2-r1/servant/servant_clock_gen.v \
	servant_1.0.2-r1/servant/servant_timer.v \
	servant_1.0.2-r1/servant/servant_gpio.v \
	servant_1.0.2-r1/servant/servant_arbiter.v \
	servant_1.0.2-r1/servant/servant_mux.v \
	servant_1.0.2-r1/servant/servant_ram.v \
	servant_1.0.2-r1/servant/servant.v \
	serving_1.0.2/serving/serving_arbiter.v \
	serving_1.0.2/serving/serving_mux.v \
	serving_1.0.2/serving/serving_ram.v \
	serving_1.0.2/serving/serving.v \
	corescore_0/rtl/wb2axis.v \
	corescore_0/rtl/base.v \
	corescore_0/rtl/axis2wb.v \
	corescore_0/rtl/emitter_mux.v \
	corescore_0/rtl/emitter_uart.v \
	corescore_0/rtl/emitter.v \
	corescore_0/rtl/corescore_gatemate_clock_gen.v \
	corescore_0/rtl/corescore_gatemate.v \
	corescore_0/rtl/gatemate_pll.v \
	corescore-corescorecore_0/corescorecore_10.v
#	corescore-corescorecore_0/corescorecore_1.v
#	corescore-corescorecore_0/corescorecore_10.v
#	corescore-corescorecore_0/corescorecore_25.v
#	corescore-corescorecore_0/corescorecore_45.v
#   corescore-corescorecore_0/corescorecore_50.v
include ../makefile.inc
