// THIS FILE IS AUTOGENERATED BY corescorecore_gen
// ANY MANUAL CHANGES WILL BE LOST
`default_nettype none
module corescorecore
   (input  wire       i_clk,
    input  wire       i_rst,
    output wire [7:0] o_tdata,
    output wire       o_tlast,
    output wire       o_tvalid,
    input  wire       i_tready);

wire [7:0] tdata;
wire [0:0] tlast;
wire [0:0] tvalid;
wire [0:0] tready;

base
  #(.memfile ("hex/core_0.hex"),
    .memsize (256))
 core_0
   (.i_clk    (i_clk),
    .i_rst    (i_rst),
    .o_tdata  (tdata[7:0]),
    .o_tlast  (tlast[0]),
    .o_tvalid (tvalid[0]),
    .i_tready (tready[0]));

axis_arb_mux
  #(.S_COUNT      (1),
    .DATA_WIDTH   (8),
    .KEEP_ENABLE  (0),
    .KEEP_WIDTH   (1),
    .ID_ENABLE    (0),
    .ID_WIDTH     (8),
    .DEST_ENABLE  (0),
    .DEST_WIDTH   (8),
    .USER_ENABLE  (0),
    .USER_WIDTH   (1),
    .ARB_TYPE     ("ROUND_ROBIN"),
    .LSB_PRIORITY ("HIGH"))
 axis_mux
   (.clk           (i_clk),
    .rst           (i_rst),
    .s_axis_tdata  (tdata),
    .s_axis_tkeep  (1'd0),
    .s_axis_tvalid (tvalid),
    .s_axis_tready (tready),
    .s_axis_tlast  (tlast),
    .s_axis_tid    (8'd0),
    .s_axis_tdest  (8'd0),
    .s_axis_tuser  (1'd0),
    .m_axis_tdata  (o_tdata),
    .m_axis_tkeep  (),
    .m_axis_tvalid (o_tvalid),
    .m_axis_tready (i_tready),
    .m_axis_tlast  (o_tlast),
    .m_axis_tid    (),
    .m_axis_tdest  (),
    .m_axis_tuser  ());

endmodule
