TEST_CASE := altair
TOP := top
YOSYS_PARAM := -nomx8 -nomult -noaddf
VERILOG_FILES := \
	top_altair.v \
	altair.v \
	i8080.v \
	mc6850.v \
	jmp_boot.v \
	ram_memory.v \
	rom_memory.v \
	simpleuart.v
include ../makefile.inc
